"""Reepo seed data — generate realistic mock repos for development and testing."""
from datetime import datetime, timedelta, timezone

from src.db import init_db, upsert_repo, DEFAULT_DB_PATH
from src.taxonomy import classify_repo
from src.analyzer import analyze_repo, record_score

SEED_REPOS = [
    {
        "github_id": 100001,
        "owner": "langchain-ai",
        "name": "langchain",
        "full_name": "langchain-ai/langchain",
        "description": "Build context-aware reasoning applications with LangChain",
        "url": "https://github.com/langchain-ai/langchain",
        "stars": 95000,
        "forks": 15200,
        "language": "Python",
        "license": "MIT",
        "topics": ["langchain", "llm", "agents", "rag", "ai"],
        "open_issues": 1200,
        "has_wiki": True,
        "homepage": "https://langchain.com",
        "readme_excerpt": "LangChain is a framework for developing applications powered by large language models (LLMs). It provides tools for chaining together LLM calls with other components to build complex AI applications.",
    },
    {
        "github_id": 100002,
        "owner": "huggingface",
        "name": "transformers",
        "full_name": "huggingface/transformers",
        "description": "State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX",
        "url": "https://github.com/huggingface/transformers",
        "stars": 135000,
        "forks": 27000,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["transformers", "pytorch", "tensorflow", "jax", "nlp", "machine-learning", "deep-learning", "huggingface"],
        "open_issues": 900,
        "has_wiki": False,
        "homepage": "https://huggingface.co/transformers",
        "readme_excerpt": "Transformers provides thousands of pretrained models for natural language processing, computer vision, audio, and multimodal tasks. The library supports PyTorch, TensorFlow, and JAX.",
    },
    {
        "github_id": 100003,
        "owner": "pytorch",
        "name": "pytorch",
        "full_name": "pytorch/pytorch",
        "description": "Tensors and Dynamic neural networks in Python with strong GPU acceleration",
        "url": "https://github.com/pytorch/pytorch",
        "stars": 84000,
        "forks": 22500,
        "language": "Python",
        "license": "BSD-3-Clause",
        "topics": ["pytorch", "deep-learning", "machine-learning", "neural-network", "gpu"],
        "open_issues": 14000,
        "has_wiki": False,
        "homepage": "https://pytorch.org",
        "readme_excerpt": "PyTorch is an open source machine learning framework that accelerates the path from research to production. It provides tensor computation with strong GPU acceleration and deep neural networks.",
    },
    {
        "github_id": 100004,
        "owner": "AUTOMATIC1111",
        "name": "stable-diffusion-webui",
        "full_name": "AUTOMATIC1111/stable-diffusion-webui",
        "description": "Stable Diffusion web UI — a browser interface for Stable Diffusion",
        "url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        "stars": 142000,
        "forks": 27000,
        "language": "Python",
        "license": "AGPL-3.0",
        "topics": ["stable-diffusion", "stable-diffusion-webui", "ai", "deep-learning", "gradio"],
        "open_issues": 2100,
        "has_wiki": True,
        "homepage": "",
        "readme_excerpt": "A web interface for Stable Diffusion, implemented using Gradio library. Supports txt2img, img2img, inpainting, outpainting, and many extensions.",
    },
    {
        "github_id": 100005,
        "owner": "ollama",
        "name": "ollama",
        "full_name": "ollama/ollama",
        "description": "Get up and running with Llama 3, Mistral, Gemma 2, and other large language models",
        "url": "https://github.com/ollama/ollama",
        "stars": 105000,
        "forks": 8300,
        "language": "Go",
        "license": "MIT",
        "topics": ["llm", "llama", "mistral", "ai", "machine-learning"],
        "open_issues": 1500,
        "has_wiki": False,
        "homepage": "https://ollama.com",
        "readme_excerpt": "Ollama makes it easy to run large language models locally. Run Llama 3, Phi 3, Mistral, Gemma 2, and other models with a simple command-line interface.",
    },
    {
        "github_id": 100006,
        "owner": "openai",
        "name": "openai-python",
        "full_name": "openai/openai-python",
        "description": "The official Python library for the OpenAI API",
        "url": "https://github.com/openai/openai-python",
        "stars": 23000,
        "forks": 3200,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["openai", "gpt", "chatgpt", "api-client", "sdk", "python"],
        "open_issues": 120,
        "has_wiki": False,
        "homepage": "https://platform.openai.com",
        "readme_excerpt": "The official Python library for the OpenAI API provides convenient access to the OpenAI REST API from any Python 3.8+ application.",
    },
    {
        "github_id": 100007,
        "owner": "microsoft",
        "name": "autogen",
        "full_name": "microsoft/autogen",
        "description": "A programming framework for agentic AI",
        "url": "https://github.com/microsoft/autogen",
        "stars": 35000,
        "forks": 5100,
        "language": "Python",
        "license": "MIT",
        "topics": ["agents", "ai-agents", "multi-agent", "llm", "autogen"],
        "open_issues": 450,
        "has_wiki": False,
        "homepage": "https://microsoft.github.io/autogen/",
        "readme_excerpt": "AutoGen is a framework for building multi-agent conversational systems. It enables the creation of autonomous agents that can collaborate to solve tasks.",
    },
    {
        "github_id": 100008,
        "owner": "crewAIInc",
        "name": "crewAI",
        "full_name": "crewAIInc/crewAI",
        "description": "Framework for orchestrating role-playing, autonomous AI agents",
        "url": "https://github.com/crewAIInc/crewAI",
        "stars": 22000,
        "forks": 3100,
        "language": "Python",
        "license": "MIT",
        "topics": ["agents", "ai-agents", "crewai", "multi-agent", "autonomous-agents"],
        "open_issues": 300,
        "has_wiki": False,
        "homepage": "https://crewai.com",
        "readme_excerpt": "CrewAI is a cutting-edge framework for orchestrating autonomous AI agents. It enables agents with defined roles to collaborate and complete complex tasks.",
    },
    {
        "github_id": 100009,
        "owner": "ggerganov",
        "name": "llama.cpp",
        "full_name": "ggerganov/llama.cpp",
        "description": "LLM inference in C/C++",
        "url": "https://github.com/ggerganov/llama.cpp",
        "stars": 72000,
        "forks": 10400,
        "language": "C++",
        "license": "MIT",
        "topics": ["llm", "llama", "ggml", "inference", "machine-learning"],
        "open_issues": 600,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "Inference of Meta's LLaMA model in pure C/C++. Supports GGUF format, quantization, and runs on CPU and GPU.",
    },
    {
        "github_id": 100010,
        "owner": "tensorflow",
        "name": "tensorflow",
        "full_name": "tensorflow/tensorflow",
        "description": "An Open Source Machine Learning Framework for Everyone",
        "url": "https://github.com/tensorflow/tensorflow",
        "stars": 186000,
        "forks": 74000,
        "language": "C++",
        "license": "Apache-2.0",
        "topics": ["tensorflow", "deep-learning", "machine-learning", "neural-network"],
        "open_issues": 2300,
        "has_wiki": False,
        "homepage": "https://tensorflow.org",
        "readme_excerpt": "TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries, and community resources.",
    },
    {
        "github_id": 100011,
        "owner": "vllm-project",
        "name": "vllm",
        "full_name": "vllm-project/vllm",
        "description": "A high-throughput and memory-efficient inference and serving engine for LLMs",
        "url": "https://github.com/vllm-project/vllm",
        "stars": 35000,
        "forks": 5200,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["llm", "inference", "serving", "gpu", "machine-learning"],
        "open_issues": 2800,
        "has_wiki": False,
        "homepage": "https://vllm.ai",
        "readme_excerpt": "vLLM is a fast and easy-to-use library for LLM inference and serving. It delivers state-of-the-art serving throughput with PagedAttention memory management.",
    },
    {
        "github_id": 100012,
        "owner": "comfyanonymous",
        "name": "ComfyUI",
        "full_name": "comfyanonymous/ComfyUI",
        "description": "The most powerful and modular stable diffusion GUI and backend",
        "url": "https://github.com/comfyanonymous/ComfyUI",
        "stars": 58000,
        "forks": 6200,
        "language": "Python",
        "license": "GPL-3.0",
        "topics": ["stable-diffusion", "gui", "ai", "deep-learning", "comfyui"],
        "open_issues": 1800,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "A powerful and modular stable diffusion GUI with a graph/nodes interface. Design and execute advanced stable diffusion pipelines without code.",
    },
    {
        "github_id": 100013,
        "owner": "run-llama",
        "name": "llama_index",
        "full_name": "run-llama/llama_index",
        "description": "LlamaIndex is a data framework for your LLM applications",
        "url": "https://github.com/run-llama/llama_index",
        "stars": 37000,
        "forks": 5300,
        "language": "Python",
        "license": "MIT",
        "topics": ["rag", "llm", "retrieval-augmented-generation", "ai", "langchain"],
        "open_issues": 400,
        "has_wiki": False,
        "homepage": "https://llamaindex.ai",
        "readme_excerpt": "LlamaIndex is a data framework for building LLM-based applications with data. It provides tools for ingesting, structuring, and accessing private or domain-specific data.",
    },
    {
        "github_id": 100014,
        "owner": "chroma-core",
        "name": "chroma",
        "full_name": "chroma-core/chroma",
        "description": "The AI-native open-source embedding database",
        "url": "https://github.com/chroma-core/chroma",
        "stars": 15000,
        "forks": 1300,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["vector-database", "embedding", "rag", "ai", "machine-learning"],
        "open_issues": 350,
        "has_wiki": False,
        "homepage": "https://trychroma.com",
        "readme_excerpt": "Chroma is the AI-native open-source embedding database. It makes it easy to build LLM applications by storing and retrieving embeddings and their metadata.",
    },
    {
        "github_id": 100015,
        "owner": "qdrant",
        "name": "qdrant",
        "full_name": "qdrant/qdrant",
        "description": "Qdrant - High-performance, massive-scale Vector Database for the next generation of AI",
        "url": "https://github.com/qdrant/qdrant",
        "stars": 21000,
        "forks": 1400,
        "language": "Rust",
        "license": "Apache-2.0",
        "topics": ["vector-database", "vector-search", "similarity", "embedding", "ai"],
        "open_issues": 200,
        "has_wiki": False,
        "homepage": "https://qdrant.tech",
        "readme_excerpt": "Qdrant is a vector similarity search engine and vector database. It provides a production-ready service with a convenient API for storing, searching, and managing vectors.",
    },
    {
        "github_id": 100016,
        "owner": "mlflow",
        "name": "mlflow",
        "full_name": "mlflow/mlflow",
        "description": "Open source platform for the machine learning lifecycle",
        "url": "https://github.com/mlflow/mlflow",
        "stars": 19000,
        "forks": 4400,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["mlops", "machine-learning", "ml-pipeline", "model-deployment", "experiment-tracking"],
        "open_issues": 800,
        "has_wiki": False,
        "homepage": "https://mlflow.org",
        "readme_excerpt": "MLflow is an open source platform for managing the end-to-end machine learning lifecycle. It tackles experimentation, reproducibility, deployment, and a central model registry.",
    },
    {
        "github_id": 100017,
        "owner": "ray-project",
        "name": "ray",
        "full_name": "ray-project/ray",
        "description": "Ray is a unified framework for scaling AI and Python applications",
        "url": "https://github.com/ray-project/ray",
        "stars": 34000,
        "forks": 5900,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["ray", "distributed-computing", "machine-learning", "reinforcement-learning", "mlops"],
        "open_issues": 3800,
        "has_wiki": False,
        "homepage": "https://ray.io",
        "readme_excerpt": "Ray is a unified framework for scaling AI and Python applications. Ray consists of a core distributed runtime and a set of AI libraries for accelerating ML workloads.",
    },
    {
        "github_id": 100018,
        "owner": "scikit-learn",
        "name": "scikit-learn",
        "full_name": "scikit-learn/scikit-learn",
        "description": "scikit-learn: machine learning in Python",
        "url": "https://github.com/scikit-learn/scikit-learn",
        "stars": 60000,
        "forks": 25500,
        "language": "Python",
        "license": "BSD-3-Clause",
        "topics": ["machine-learning", "data-science", "statistics", "python"],
        "open_issues": 2400,
        "has_wiki": False,
        "homepage": "https://scikit-learn.org",
        "readme_excerpt": "scikit-learn is a Python module for machine learning built on top of SciPy. It provides simple and efficient tools for predictive data analysis.",
    },
    {
        "github_id": 100019,
        "owner": "openai",
        "name": "whisper",
        "full_name": "openai/whisper",
        "description": "Robust Speech Recognition via Large-Scale Weak Supervision",
        "url": "https://github.com/openai/whisper",
        "stars": 72000,
        "forks": 8500,
        "language": "Python",
        "license": "MIT",
        "topics": ["speech-recognition", "deep-learning", "machine-learning", "nlp", "openai"],
        "open_issues": 350,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "Whisper is a general-purpose speech recognition model. It is trained on a large dataset of diverse audio and is also a multitask model that can perform speech translation and language identification.",
    },
    {
        "github_id": 100020,
        "owner": "gradio-app",
        "name": "gradio",
        "full_name": "gradio-app/gradio",
        "description": "Build and share delightful machine learning apps, all in Python",
        "url": "https://github.com/gradio-app/gradio",
        "stars": 35000,
        "forks": 2600,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["gradio", "machine-learning", "demo", "web-app", "python"],
        "open_issues": 600,
        "has_wiki": False,
        "homepage": "https://gradio.app",
        "readme_excerpt": "Gradio is the fastest way to demo your machine learning model with a friendly web interface so that anyone can use it.",
    },
    {
        "github_id": 100021,
        "owner": "streamlit",
        "name": "streamlit",
        "full_name": "streamlit/streamlit",
        "description": "Streamlit — A faster way to build and share data apps",
        "url": "https://github.com/streamlit/streamlit",
        "stars": 36000,
        "forks": 3100,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["streamlit", "data-science", "web-app", "python", "machine-learning"],
        "open_issues": 700,
        "has_wiki": False,
        "homepage": "https://streamlit.io",
        "readme_excerpt": "Streamlit turns data scripts into shareable web apps in minutes. All in pure Python. No frontend experience required.",
    },
    {
        "github_id": 100022,
        "owner": "Significant-Gravitas",
        "name": "AutoGPT",
        "full_name": "Significant-Gravitas/AutoGPT",
        "description": "AutoGPT is the vision of accessible AI for everyone",
        "url": "https://github.com/Significant-Gravitas/AutoGPT",
        "stars": 168000,
        "forks": 44000,
        "language": "Python",
        "license": "MIT",
        "topics": ["autogpt", "ai-agents", "autonomous-agents", "gpt", "openai"],
        "open_issues": 100,
        "has_wiki": False,
        "homepage": "https://agpt.co",
        "readme_excerpt": "AutoGPT is an experimental open-source application showcasing the capabilities of GPT-4 as an autonomous AI agent. It chains together LLM thoughts to achieve whatever goal you set.",
    },
    {
        "github_id": 100023,
        "owner": "deepset-ai",
        "name": "haystack",
        "full_name": "deepset-ai/haystack",
        "description": "AI orchestration framework to build customizable, production-ready LLM applications",
        "url": "https://github.com/deepset-ai/haystack",
        "stars": 18000,
        "forks": 1900,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["rag", "llm", "nlp", "retrieval-augmented-generation", "ai"],
        "open_issues": 250,
        "has_wiki": False,
        "homepage": "https://haystack.deepset.ai",
        "readme_excerpt": "Haystack is an open-source framework for building production-ready LLM applications, retrieval-augmented generative pipelines, and state-of-the-art search systems.",
    },
    {
        "github_id": 100024,
        "owner": "keras-team",
        "name": "keras",
        "full_name": "keras-team/keras",
        "description": "Deep Learning for humans",
        "url": "https://github.com/keras-team/keras",
        "stars": 62000,
        "forks": 19500,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["keras", "deep-learning", "machine-learning", "neural-network", "tensorflow"],
        "open_issues": 300,
        "has_wiki": False,
        "homepage": "https://keras.io",
        "readme_excerpt": "Keras is a deep learning API written in Python, running on top of the machine learning platform TensorFlow. It provides industry-strength performance and scalability.",
    },
    {
        "github_id": 100025,
        "owner": "ultralytics",
        "name": "ultralytics",
        "full_name": "ultralytics/ultralytics",
        "description": "Ultralytics YOLO11 — state of the art real-time object detection",
        "url": "https://github.com/ultralytics/ultralytics",
        "stars": 34000,
        "forks": 6500,
        "language": "Python",
        "license": "AGPL-3.0",
        "topics": ["computer-vision", "object-detection", "yolo", "deep-learning", "pytorch"],
        "open_issues": 1000,
        "has_wiki": False,
        "homepage": "https://ultralytics.com",
        "readme_excerpt": "Ultralytics YOLO is the latest version of the acclaimed real-time object detection and image segmentation model. Supports detection, segmentation, classification, and pose estimation.",
    },
    {
        "github_id": 100026,
        "owner": "huggingface",
        "name": "datasets",
        "full_name": "huggingface/datasets",
        "description": "The largest hub of ready-to-use datasets for ML models",
        "url": "https://github.com/huggingface/datasets",
        "stars": 19000,
        "forks": 2600,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["datasets", "machine-learning", "nlp", "huggingface", "data-processing"],
        "open_issues": 600,
        "has_wiki": False,
        "homepage": "https://huggingface.co/docs/datasets",
        "readme_excerpt": "Datasets is a lightweight library providing easy access to thousands of datasets for machine learning. It offers smart caching and memory-mapping.",
    },
    {
        "github_id": 100027,
        "owner": "bentoml",
        "name": "BentoML",
        "full_name": "bentoml/BentoML",
        "description": "The easiest way to serve AI apps and models",
        "url": "https://github.com/bentoml/BentoML",
        "stars": 7100,
        "forks": 790,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["model-serving", "mlops", "deployment", "inference", "machine-learning"],
        "open_issues": 150,
        "has_wiki": False,
        "homepage": "https://bentoml.com",
        "readme_excerpt": "BentoML is an open-source model serving framework for building production-ready AI applications. It simplifies the process of deploying ML models as API endpoints.",
    },
    {
        "github_id": 100028,
        "owner": "explosion",
        "name": "spaCy",
        "full_name": "explosion/spaCy",
        "description": "Industrial-strength Natural Language Processing (NLP) in Python",
        "url": "https://github.com/explosion/spaCy",
        "stars": 30000,
        "forks": 4400,
        "language": "Python",
        "license": "MIT",
        "topics": ["nlp", "natural-language-processing", "machine-learning", "deep-learning", "python"],
        "open_issues": 100,
        "has_wiki": False,
        "homepage": "https://spacy.io",
        "readme_excerpt": "spaCy is a library for advanced Natural Language Processing in Python and Cython. It's built on the very latest research, and was designed from day one to be used in real products.",
    },
    {
        "github_id": 100029,
        "owner": "Lightning-AI",
        "name": "pytorch-lightning",
        "full_name": "Lightning-AI/pytorch-lightning",
        "description": "Pretrain, finetune, and deploy AI models on any hardware",
        "url": "https://github.com/Lightning-AI/pytorch-lightning",
        "stars": 28000,
        "forks": 3400,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["pytorch", "deep-learning", "machine-learning", "training", "gpu"],
        "open_issues": 700,
        "has_wiki": False,
        "homepage": "https://lightning.ai",
        "readme_excerpt": "PyTorch Lightning is the deep learning framework for professional AI researchers and machine learning engineers who need maximum flexibility while keeping code clean.",
    },
    {
        "github_id": 100030,
        "owner": "lm-sys",
        "name": "FastChat",
        "full_name": "lm-sys/FastChat",
        "description": "An open platform for training, serving, and evaluating large language models",
        "url": "https://github.com/lm-sys/FastChat",
        "stars": 37000,
        "forks": 4600,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["llm", "chatbot", "serving", "evaluation", "machine-learning"],
        "open_issues": 800,
        "has_wiki": False,
        "homepage": "https://chat.lmsys.org",
        "readme_excerpt": "FastChat is an open platform for training, serving, and evaluating large language model based chatbots. It powers Chatbot Arena, the world's leading LLM evaluation platform.",
    },
    {
        "github_id": 100031,
        "owner": "facebookresearch",
        "name": "faiss",
        "full_name": "facebookresearch/faiss",
        "description": "A library for efficient similarity search and clustering of dense vectors",
        "url": "https://github.com/facebookresearch/faiss",
        "stars": 32000,
        "forks": 3700,
        "language": "C++",
        "license": "MIT",
        "topics": ["vector-search", "similarity", "embedding", "machine-learning", "gpu"],
        "open_issues": 400,
        "has_wiki": True,
        "homepage": "https://faiss.ai",
        "readme_excerpt": "Faiss is a library for efficient similarity search and clustering of dense vectors. It contains algorithms that search in sets of vectors of any size.",
    },
    {
        "github_id": 100032,
        "owner": "dagger",
        "name": "dagger",
        "full_name": "dagger/dagger",
        "description": "An engine to run your pipelines in containers",
        "url": "https://github.com/dagger/dagger",
        "stars": 11500,
        "forks": 1200,
        "language": "Go",
        "license": "Apache-2.0",
        "topics": ["ci-cd", "containers", "pipeline", "devops"],
        "open_issues": 300,
        "has_wiki": False,
        "homepage": "https://dagger.io",
        "readme_excerpt": "Dagger is a programmable CI/CD engine that runs your pipelines in containers. Define your pipeline as code, then run it anywhere.",
    },
    {
        "github_id": 100033,
        "owner": "OpenDevin",
        "name": "OpenDevin",
        "full_name": "OpenDevin/OpenDevin",
        "description": "An open-source project aiming to replicate Devin, an autonomous AI software engineer",
        "url": "https://github.com/OpenDevin/OpenDevin",
        "stars": 34000,
        "forks": 3900,
        "language": "Python",
        "license": "MIT",
        "topics": ["ai-agents", "autonomous-agents", "coding", "llm", "agents"],
        "open_issues": 250,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "OpenDevin aims to build an autonomous AI software engineer that can write code, fix bugs, and complete software engineering tasks with minimal human intervention.",
    },
    {
        "github_id": 100034,
        "owner": "anthropics",
        "name": "anthropic-sdk-python",
        "full_name": "anthropics/anthropic-sdk-python",
        "description": "Python SDK for the Anthropic API",
        "url": "https://github.com/anthropics/anthropic-sdk-python",
        "stars": 1800,
        "forks": 250,
        "language": "Python",
        "license": "MIT",
        "topics": ["anthropic", "claude", "sdk", "api-client", "python"],
        "open_issues": 45,
        "has_wiki": False,
        "homepage": "https://docs.anthropic.com",
        "readme_excerpt": "The official Python SDK for the Anthropic API. Provides type-safe access to Claude and other Anthropic models.",
    },
    {
        "github_id": 100035,
        "owner": "microsoft",
        "name": "DeepSpeed",
        "full_name": "microsoft/DeepSpeed",
        "description": "DeepSpeed is a deep learning optimization library for distributed training and inference",
        "url": "https://github.com/microsoft/DeepSpeed",
        "stars": 35000,
        "forks": 4100,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["deep-learning", "distributed-training", "pytorch", "gpu", "machine-learning"],
        "open_issues": 1700,
        "has_wiki": False,
        "homepage": "https://www.deepspeed.ai",
        "readme_excerpt": "DeepSpeed is a deep learning optimization library that makes distributed training and inference easy, efficient, and effective. It supports massive model sizes with ZeRO optimization.",
    },
    {
        "github_id": 100036,
        "owner": "XingangPan",
        "name": "DragGAN",
        "full_name": "XingangPan/DragGAN",
        "description": "Official Code for DragGAN",
        "url": "https://github.com/XingangPan/DragGAN",
        "stars": 35600,
        "forks": 3300,
        "language": "Python",
        "license": "MIT",
        "topics": ["gan", "deep-learning", "computer-vision", "image-editing", "ai"],
        "open_issues": 80,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "Drag Your GAN: Interactive Point-based Manipulation on the Generative Image Manifold. This is the official implementation of DragGAN.",
    },
    {
        "github_id": 100037,
        "owner": "milvus-io",
        "name": "milvus",
        "full_name": "milvus-io/milvus",
        "description": "A cloud-native vector database for scalable similarity search",
        "url": "https://github.com/milvus-io/milvus",
        "stars": 31000,
        "forks": 2900,
        "language": "Go",
        "license": "Apache-2.0",
        "topics": ["vector-database", "vector-search", "similarity", "embedding", "machine-learning"],
        "open_issues": 500,
        "has_wiki": False,
        "homepage": "https://milvus.io",
        "readme_excerpt": "Milvus is an open-source vector database built for scalable similarity search. It supports embedding search, vector analytics, and hybrid queries.",
    },
    {
        "github_id": 100038,
        "owner": "wandb",
        "name": "wandb",
        "full_name": "wandb/wandb",
        "description": "A tool for visualizing and tracking your machine learning experiments",
        "url": "https://github.com/wandb/wandb",
        "stars": 9200,
        "forks": 680,
        "language": "Python",
        "license": "MIT",
        "topics": ["mlops", "experiment-tracking", "visualization", "machine-learning", "monitoring"],
        "open_issues": 500,
        "has_wiki": False,
        "homepage": "https://wandb.ai",
        "readme_excerpt": "Weights & Biases helps AI developers build better models faster. Track and visualize all the pieces of your machine learning pipeline.",
    },
    {
        "github_id": 100039,
        "owner": "openai",
        "name": "gym",
        "full_name": "openai/gym",
        "description": "A toolkit for developing and comparing reinforcement learning algorithms",
        "url": "https://github.com/openai/gym",
        "stars": 35000,
        "forks": 8700,
        "language": "Python",
        "license": "MIT",
        "topics": ["reinforcement-learning", "openai", "machine-learning", "python"],
        "open_issues": 400,
        "has_wiki": False,
        "homepage": "https://www.gymlibrary.dev",
        "readme_excerpt": "OpenAI Gym is a toolkit for developing and comparing reinforcement learning algorithms. It provides a standardized set of environments.",
    },
    {
        "github_id": 100040,
        "owner": "Stability-AI",
        "name": "stablediffusion",
        "full_name": "Stability-AI/stablediffusion",
        "description": "High-Resolution Image Synthesis with Latent Diffusion Models",
        "url": "https://github.com/Stability-AI/stablediffusion",
        "stars": 39000,
        "forks": 5100,
        "language": "Python",
        "license": "MIT",
        "topics": ["stable-diffusion", "deep-learning", "generative-ai", "computer-vision"],
        "open_issues": 900,
        "has_wiki": False,
        "homepage": "https://stability.ai",
        "readme_excerpt": "This repository contains Stable Diffusion models for high-resolution image synthesis using latent diffusion models with attention mechanisms.",
    },
    {
        "github_id": 100041,
        "owner": "microsoft",
        "name": "semantic-kernel",
        "full_name": "microsoft/semantic-kernel",
        "description": "Integrate cutting-edge LLM technology quickly and easily into your apps",
        "url": "https://github.com/microsoft/semantic-kernel",
        "stars": 22000,
        "forks": 3300,
        "language": "C#",
        "license": "MIT",
        "topics": ["llm", "ai", "sdk", "plugin", "agents"],
        "open_issues": 300,
        "has_wiki": False,
        "homepage": "https://learn.microsoft.com/semantic-kernel",
        "readme_excerpt": "Semantic Kernel is an SDK that integrates Large Language Models like OpenAI, Azure OpenAI, and Hugging Face with conventional programming languages.",
    },
    {
        "github_id": 100042,
        "owner": "xai-org",
        "name": "grok-1",
        "full_name": "xai-org/grok-1",
        "description": "Grok open release",
        "url": "https://github.com/xai-org/grok-1",
        "stars": 49000,
        "forks": 8300,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["llm", "grok", "machine-learning", "ai"],
        "open_issues": 110,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "This repository contains the model weights and architecture for Grok-1, a 314B parameter Mixture-of-Experts model released by xAI.",
    },
    {
        "github_id": 100043,
        "owner": "labmlai",
        "name": "annotated_deep_learning_paper_implementations",
        "full_name": "labmlai/annotated_deep_learning_paper_implementations",
        "description": "Implementations with side-by-side notes of 60+ deep learning papers",
        "url": "https://github.com/labmlai/annotated_deep_learning_paper_implementations",
        "stars": 56000,
        "forks": 5800,
        "language": "Python",
        "license": "MIT",
        "topics": ["deep-learning", "pytorch", "machine-learning", "transformers", "nlp"],
        "open_issues": 40,
        "has_wiki": False,
        "homepage": "https://nn.labml.ai",
        "readme_excerpt": "This is a collection of simple PyTorch implementations of neural networks and related algorithms. These implementations are documented with explanations.",
    },
    {
        "github_id": 100044,
        "owner": "doccano",
        "name": "doccano",
        "full_name": "doccano/doccano",
        "description": "Open source annotation tool for machine learning practitioners",
        "url": "https://github.com/doccano/doccano",
        "stars": 9500,
        "forks": 1600,
        "language": "Python",
        "license": "MIT",
        "topics": ["annotation", "labeling", "nlp", "machine-learning", "dataset"],
        "open_issues": 200,
        "has_wiki": False,
        "homepage": "https://doccano.github.io/doccano/",
        "readme_excerpt": "Doccano is an open source text annotation tool for human. It provides annotation features for text classification, sequence labeling and sequence to sequence tasks.",
    },
    {
        "github_id": 100045,
        "owner": "langgenius",
        "name": "dify",
        "full_name": "langgenius/dify",
        "description": "Dify is an open-source LLM app development platform",
        "url": "https://github.com/langgenius/dify",
        "stars": 52000,
        "forks": 7600,
        "language": "TypeScript",
        "license": "Apache-2.0",
        "topics": ["llm", "ai", "chatbot", "agents", "rag"],
        "open_issues": 400,
        "has_wiki": False,
        "homepage": "https://dify.ai",
        "readme_excerpt": "Dify is an open-source LLM app development platform. It combines AI workflow, RAG pipeline, agent capabilities, model management, and observability features.",
    },
    {
        "github_id": 100046,
        "owner": "fixie-ai",
        "name": "ultravox",
        "full_name": "fixie-ai/ultravox",
        "description": "A fast multimodal LLM for real-time voice",
        "url": "https://github.com/fixie-ai/ultravox",
        "stars": 1800,
        "forks": 140,
        "language": "Python",
        "license": "MIT",
        "topics": ["llm", "speech", "multimodal", "voice", "ai"],
        "open_issues": 30,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "Ultravox is a fast multimodal LLM designed for real-time voice conversations. It processes audio directly without a separate speech-to-text step.",
    },
    {
        "github_id": 100047,
        "owner": "microsoft",
        "name": "JARVIS",
        "full_name": "microsoft/JARVIS",
        "description": "JARVIS - a system to connect LLMs with ML community",
        "url": "https://github.com/microsoft/JARVIS",
        "stars": 23500,
        "forks": 2000,
        "language": "Python",
        "license": "MIT",
        "topics": ["ai-agents", "llm", "agents", "machine-learning", "chatgpt-plugin"],
        "open_issues": 70,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "JARVIS is a system that connects LLMs with the machine learning community. It uses ChatGPT as a controller to manage existing AI models for solving complicated AI tasks.",
    },
    {
        "github_id": 100048,
        "owner": "huggingface",
        "name": "tokenizers",
        "full_name": "huggingface/tokenizers",
        "description": "Fast State-of-the-Art Tokenizers optimized for Research and Production",
        "url": "https://github.com/huggingface/tokenizers",
        "stars": 9100,
        "forks": 800,
        "language": "Rust",
        "license": "Apache-2.0",
        "topics": ["tokenizer", "nlp", "machine-learning", "huggingface", "rust"],
        "open_issues": 250,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "Provides an implementation of today's most used tokenizers, with a focus on performance and versatility. Bind to Rust for fast tokenization.",
    },
    {
        "github_id": 100049,
        "owner": "dummy-org",
        "name": "abandoned-ml-project",
        "full_name": "dummy-org/abandoned-ml-project",
        "description": "An old machine learning experiment",
        "url": "https://github.com/dummy-org/abandoned-ml-project",
        "stars": 5,
        "forks": 1,
        "language": "Python",
        "license": None,
        "topics": ["machine-learning"],
        "open_issues": 0,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "Old project.",
    },
    {
        "github_id": 100050,
        "owner": "tiny-dev",
        "name": "tiny-chatbot",
        "full_name": "tiny-dev/tiny-chatbot",
        "description": "A minimal chatbot built with Python",
        "url": "https://github.com/tiny-dev/tiny-chatbot",
        "stars": 15,
        "forks": 3,
        "language": "Python",
        "license": "MIT",
        "topics": ["chatbot", "python", "nlp"],
        "open_issues": 2,
        "has_wiki": False,
        "homepage": "",
        "readme_excerpt": "A simple chatbot example using basic NLP techniques.",
    },
]


def _add_timestamps(repo: dict, age_days: int, active: bool) -> dict:
    """Add realistic timestamps to a seed repo."""
    now = datetime.now(timezone.utc)
    created = now - timedelta(days=age_days)
    if active:
        pushed = now - timedelta(days=max(1, age_days // 30))
    else:
        pushed = now - timedelta(days=max(age_days // 2, 180))
    updated = pushed

    repo["created_at"] = created.isoformat()
    repo["updated_at"] = updated.isoformat()
    repo["pushed_at"] = pushed.isoformat()
    return repo


def generate_seed_repos() -> list[dict]:
    """Generate 50 seed repos with timestamps and classifications."""
    repos = []
    for i, repo in enumerate(SEED_REPOS):
        repo = dict(repo)
        is_popular = repo.get("stars", 0) > 100
        age_days = 365 + (i * 30) % 1000
        repo = _add_timestamps(repo, age_days, active=is_popular)

        primary, secondary = classify_repo(
            repo["name"],
            repo.get("description", ""),
            repo.get("topics", []),
            repo.get("readme_excerpt", ""),
        )
        repo["category_primary"] = primary
        repo["categories_secondary"] = secondary
        repos.append(repo)
    return repos


def seed_database(db_path: str = DEFAULT_DB_PATH) -> int:
    """Seed the database with mock repos and analyze them. Returns count inserted."""
    from src.db import init_db, upsert_repo

    init_db(db_path)
    repos = generate_seed_repos()
    count = 0
    for repo in repos:
        repo_id = upsert_repo(repo, db_path)
        result = analyze_repo(repo)
        record_score(repo_id, result["reepo_score"], result["score_breakdown"], db_path)
        count += 1
    return count
